# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0001_squashed_0005_auto_20150809_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applinews',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Software news (item)', 'verbose_name_plural': 'Software news'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_on'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookaudience',
            options={'verbose_name': 'Audience', 'verbose_name_plural': 'Audiences'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'ordering': ['label'], 'verbose_name': 'Book category', 'verbose_name_plural': 'Book categories'},
        ),
        migrations.AlterModelOptions(
            name='bookcondition',
            options={'verbose_name': 'Book condition', 'verbose_name_plural': 'Book conditions'},
        ),
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'ordering': ['number'], 'verbose_name': 'Book sample', 'verbose_name_plural': 'Book samples'},
        ),
        migrations.AlterModelOptions(
            name='bookcopyorigin',
            options={'verbose_name': 'Book origin', 'verbose_name_plural': 'Book origins'},
        ),
        migrations.AlterModelOptions(
            name='booksubcategory',
            options={'ordering': ['label'], 'verbose_name': 'Book sub-category', 'verbose_name_plural': 'Book sub-categories'},
        ),
        migrations.AlterModelOptions(
            name='booktag',
            options={'verbose_name': 'Book tag', 'verbose_name_plural': 'Book tags'},
        ),
        migrations.AlterModelOptions(
            name='generalconfiguration',
            options={'verbose_name': 'Global settings of the software', 'verbose_name_plural': 'Global settings of the software'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Reader', 'verbose_name_plural': 'Readers'},
        ),
        migrations.AlterModelOptions(
            name='readerborrow',
            options={'ordering': ['-borrow_due_date'], 'verbose_name': 'Reader borrowing', 'verbose_name_plural': 'Reader borrowings'},
        ),
        migrations.AlterField(
            model_name='author',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_isbn_import',
            field=models.BooleanField(default=False, verbose_name='ISBN import'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='book',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='book',
            name='audiences',
            field=models.ManyToManyField(to='alessandria.BookAudience', verbose_name='Audience'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='alessandria.Author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alessandria.BookCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='classif_mark',
            field=models.CharField(max_length=10, verbose_name='Classification mark'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='alessandria/upload', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Title edition'),
        ),
        migrations.AlterField(
            model_name='book',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (inches)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_isbn_import',
            field=models.BooleanField(default=False, verbose_name='ISBN import'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_nb',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alessandria.Language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(verbose_name='Publishing date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(to='alessandria.Publisher', verbose_name='Publishers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alessandria.Book', verbose_name='Linked to'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alessandria.BookSubCategory', verbose_name='Sub-category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='alessandria.BookTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alessandria.Book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alessandria.BookCondition', verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='disabled_on',
            field=models.DateField(blank=True, null=True, verbose_name='Took out on'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alessandria.BookCopyOrigin', verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='price_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date (price)'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='registered_on',
            field=models.DateField(verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='appli_name',
            field=models.TextField(default='Alessandria', verbose_name='Software name'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='default_country',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='Default country'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_addr1',
            field=models.CharField(max_length=30, verbose_name='Library address 1'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_addr2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Library address 2'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_city',
            field=models.CharField(max_length=30, verbose_name='Library city'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Library country'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Library e-mail'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_name',
            field=models.CharField(max_length=80, verbose_name='Library name'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Library phone'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_website',
            field=models.URLField(blank=True, null=True, verbose_name='Library website'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='library_zip',
            field=models.CharField(max_length=10, verbose_name='Library zip code'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='max_borrow_days',
            field=models.PositiveSmallIntegerField(default=21, verbose_name='Maximal borrowing days'),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='nav_history',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Navigation history'),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='is_isbn_import',
            field=models.BooleanField(default=False, verbose_name='ISBN import'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='addr1',
            field=models.CharField(max_length=30, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='addr2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='birthday',
            field=models.DateField(verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='disabled_on',
            field=models.DateField(blank=True, null=True, verbose_name='Disabled on'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='inscription_date',
            field=models.DateField(verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='sex',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=3, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='zip',
            field=models.CharField(max_length=10, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='readerborrow',
            name='bookcopy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alessandria.BookCopy', verbose_name='Sample'),
        ),
        migrations.AlterField(
            model_name='readerborrow',
            name='borrow_due_date',
            field=models.DateField(verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='readerborrow',
            name='borrowed_date',
            field=models.DateField(verbose_name='Borrowed on'),
        ),
        migrations.AlterField(
            model_name='readerborrow',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alessandria.Reader', verbose_name='Reader'),
        ),
        migrations.AlterField(
            model_name='readerborrow',
            name='returned_on',
            field=models.DateField(blank=True, null=True, verbose_name='Returned on'),
        ),
    ]
