# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 04:33
from __future__ import unicode_literals

from django.db import migrations

from alessandria.models import Author, Reader, Publisher


def names_to_title(apps, schema_editor):
    for author in Author.objects.all():
        author.last_name = author.last_name.strip().title()
        author.save()

    for publisher in Publisher.objects.all():
        publisher.name = publisher.name.strip().title()
        publisher.save()

    for reader in Reader.objects.all():
        reader.last_name = reader.last_name.strip().title()
        reader.save()


class Migration(migrations.Migration):
    dependencies = [
        ('alessandria', '0002_auto_20170515_0649'),
    ]

    operations = [
        migrations.RunPython(names_to_title),
    ]
