# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0003_auto_20170521_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
    ]
