# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0004_auto_20170712_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audiences',
            field=models.ManyToManyField(blank=True, to='alessandria.BookAudience', verbose_name='Audience'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='alessandria.Author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(blank=True, to='alessandria.Publisher', verbose_name='Publishers'),
        ),
    ]
