# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0006_auto_20170712_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='alessandria.Author', verbose_name='Authors'),
        ),
    ]
