# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0007_auto_20170712_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='classif_mark',
            field=models.CharField(blank=True, help_text='Corresponds to serial number or internal reference', max_length=10, null=True, verbose_name='Classification mark'),
        ),
    ]
