# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0009_auto_20180117_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uuid',
            field=models.CharField(default='', max_length=50, verbose_name='Unique Id'),
            preserve_default=False,
        ),
    ]
