# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0010_book_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uuid',
            new_name='_uuid',
        ),
    ]
