# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0011_auto_20180509_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='alessandria/upload/qrcode', verbose_name='QR Code'),
        ),
    ]
