# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0013_auto_20180511_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('withdrawed', 'Withdrawed')], default='available', max_length=32, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='book',
            name='classif_mark',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Classification mark'),
        ),
    ]
