# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0015_auto_20180807_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='manufacturer_ref',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Manufacturer Reference'),
        ),
    ]
