# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0017_auto_20180809_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed')], default='available', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('good_condition', 'Good Condition'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('withdrawed', 'Withdrawed')], default='good_condition', max_length=32, verbose_name='state'),
        ),
    ]
