# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0018_auto_20180809_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('borrowed', 'Borrowed')], default='available', max_length=32, verbose_name='status'),
        ),
    ]
