# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-23 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alessandria', '0019_auto_20180809_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='url'),
        ),
    ]
